export const ERROR_CONSTANTS = {
  // USER AUTH
  USER_AUTH_ERROR: 'USER_AUTH_ERROR',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_PASSWORD_INCORRECT: 'USER_PASSWORD_INCORRECT',
  USER_PASSWORD_REQUIRED: 'USER_PASSWORD_REQUIRED',
  USER_PASSWORD_TOO_SHORT: 'USER_PASSWORD_TOO_SHORT',
  USER_PASSWORD_TOO_LONG: 'USER_PASSWORD_TOO_LONG',

  // OTHER ERRORS
  ERROR_CODE_NOT_FOUND: 'NOT_FOUND',

};
